name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Instalar dependencias
        run: |
          mvn dependency:go-offline -Dmaven.test.skip=true -Dspring.jvm.memory="-Xmx512m -Xms256m"

      - name: Compilar aplicação
        run: mvn clean package -DskipTests -Dmaven.test.skip=true -Dspring.jvm.memory="-Xmx512m -Xms256m"
          

